# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test examples

on:
  pull_request:
  schedule:
    # Use odd number of minutes, because GitHub says the start of the hour is a
    # high-load time.
    - cron: '17 0 * * 0'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        sudo apt-get install libhdf5-dev libnetcdf-dev
        python -m pip install --upgrade pip
        pip install --upgrade xbout jupyter
    - name: Test examples
      run: |
        # The brackets are needed so the whole command returns 1 if any notebook fails
        (for example in */*.ipynb; do jupyter nbconvert --to python --execute $example || exit 1; done)
        # The brackets are needed so the whole command returns 1 if any script fails
        (for example in */*.py; do python $example || exit 1; done)
